### ISSUE TITLE
cannot find module 'log'

### ISSUE THREAD

**Issue by kof** [LearnBoost/cluster#14]
node version v0.3.7, macos

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'log'
    at Function._resolveFilename (module.js:204:11)
    at Function._load (module.js:162:25)
    at require (module.js:231:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/cluster/0.0.2/package/lib/plugins/logger.js:13:11)
    at Module._compile (module.js:287:26)
    at Object..js (module.js:293:10)
    at Module.load (module.js:219:31)
    at Function._load (module.js:186:10)
    at require (module.js:231:19)
    at Function.logger (/usr/local/lib/node/.npm/cluster/0.0.2/package/lib/cluster.js:46:12)

**Comment by kof** [comment]
is it your other module, "log", which I can see in npm? then you should add it to dependencies in package.json

**Comment by gflarity** [comment]
yes, it's missing  -> https://github.com/visionmedia/log.js

after adding it I get the following though:

events.js:23
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: ENOENT, No such file or directory '/Users/geoff/git/sandbox/logs/master.log'

**Comment by tj** [comment]
Added log to package.json. Closed by c1b20c5e9c0a4be5fd6925b8dc7e09d75536d9f1

**Comment by tj** [comment]
grr npm
