### ISSUE TITLE
throw e; // process.nextTick error, or 'error' event on first tick

### ISSUE THREAD

**Issue by Danielss89** [LearnBoost/cluster#176]
[root@sccups home]# nvm use v0.6.6
Now using node v0.6.6
[root@sccups home]# cd /var/www/vhosts/sccups.com/httpdocs/library/nodejs
[root@sccups nodejs]# node server.js
   info  - socket.io started

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: No such module
    at Object.<anonymous> (/root/node_modules/cluster/lib/worker.js:14:23)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/root/node_modules/cluster/lib/master.js:12:14)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)

**Comment by manubo** [comment]
I am using node v0.6.6 as well and get exactly the same error with:

<pre>
$ node cluster/examples/single.js
</pre>


Seems the statement <code>process.binding('net')</code> in worker.js causes the problem. But I can't help, just started with node.js :-)

**Comment by telendt** [comment]
Currently cluster doesn't support node > 0.4.

**Comment by manubo** [comment]
Right, did not check that.
Just saw that since version 0.6, node supports multiple processes on its own: http://nodejs.org/docs/v0.6.6/api/cluster.html
