### ISSUE TITLE
cluster('app') TypeError: object is not a function

### ISSUE THREAD

**Issue by durban89** [LearnBoost/cluster#191]
davidzhang@davidzhang:~/nodejs/node-blog$ node server.js
/Users/davidzhang/Nodejs/node-blog/server.js:2
cluster('app')
^
TypeError: object is not a function
    at Object.<anonymous> (/Users/davidzhang/Nodejs/node-blog/server.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by alex88** [comment]
Same here

**Comment by Yuliang-Lee** [comment]
cluster has already built in Node.js.

**Comment by shumphrey** [comment]
To clarify earlier comment, the error reported here is from the cluster module provided by nodejs not the cluster module provided here.
See nodejs API docs not this module's docs.

**Comment by ghost** [comment]
bump

**Comment by JeremyCraigMartinez** [comment]
bump
