### ISSUE TITLE
tests or examples not running

### ISSUE THREAD

**Issue by ikouchiha47** [LearnBoost/cluster#197]
cluster git:(master) ✗ make test

   test.basic.js cluster/lib/worker.js:14
  , binding = process.binding('net')
                      ^

Error: No such module: net
    at Error (native)
    at Object.<anonymous> (cluster/lib/worker.js:14:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (cluster/lib/master.js:12:14)
    at Module._compile (module.js:409:26)
make: **\* [test] Error 1

**Comment by esseybook2** [comment]
Cursed native artifacts piute in blood lines
