### ISSUE TITLE
Crash on restart by SIGUSR2

### ISSUE THREAD

**Issue by ghost** [LearnBoost/cluster#71]
```
/usr/lib/node/.npm/cluster/0.5.3/package/lib/plugins/repl.js:89
  if (server.fd) server.close();
            ^
TypeError: Cannot read property 'fd' of undefined
at Master.<anonymous> (/usr/lib/node/.npm/cluster/0.5.3/package/lib/plugins/repl.js:89:17)
at Master.emit (events.js:81:20)
at Server.<anonymous> (/usr/lib/node/.npm/cluster/0.5.3/package/lib/master.js:691:10)
at Server.emit (events.js:61:17)
at net.js:1138:12
```

crash after restart by sending signal SIGUSR2 to master pid
Gentoo and Mac 10.6.7, node 0.4.4, cluster from npm at 3.03.2011

**Comment by tj** [comment]
hmm interesting, will look into it. I assume you were passing the filename rather than the server object?
